/* ═══════════════════════════════════════════════════
   Calc Labz — Client-side Calculation Registry
   AUTO-GENERATED — Do not edit manually
   Maps calculator IDs → calc functions on the CLIENT SIDE.
   ═══════════════════════════════════════════════════ */

import { CalcFunction } from '@/types/calculator';
import {
  calcEMI, calcSIP, calcGST, calcPreGST, calcCompoundInterest, calcSimpleInterest, calcIncomeTax, calcROI, calcPPF, calcFD, calcMortgage, calcCarLoan, calcBreakeven, calcInflation, calcSWP, calcLumpsum, calcNPS, calcGratuity, calcHRA, calcCAGR, calcCreditCard, calcNetWorth, calcTDS, calcEPF, calcProfitLoss, calcStockReturn, calcMutualFundReturns, calcTaxRegime, calcCapitalGains, calcPrepayment, calcStepUpSIP, calcSavingsGoal, calcDividendYield, calcGoldInvestment, calcRD, calcXIRR, calcLoanEligibility, calcBalanceTransfer, calcSSY, calcSCSS, calcAdvanceTax, calcInhandSalary, calcCtcBreakup, calcSalaryComparison, calcGoalSIP, calcElssReturns, calcNSC, calcAPY, calcBrokerage, calcTaxSaving, calcRetirementCorpus, calcSalaryHike, calcFIRE, calcDebtAvalanche, calcEmergencyFund, calcRentVsBuy, calcCarLeaseVsBuy, calcHomeDownPayment, calcLoanCompare, calcRefinance, calcCreditUtil, calcInsuranceNeed, calcNpvIrr, calcBondYield, calcOptionProfit, calcForexPip, calcPortfolioRebalance, calcAssetAllocation, calcMonteCarlo, calcInflationGoal, calcBusinessLoan, calcGstInvoice, calcEsopTax, calcFreelanceTax, calcTcsRemittance, calcSec80c, calcHraVsHomeLoan, calcProfTax, calcLeaveEncash, calcSGB, calcFoTurnover, calcPresumptiveTax, calcHomeLoanTaxBenefit, calcIndexedCost, calcGoldComparison, calcRentYield,
  calcEmiVsTenure, calcRuleOf72, calcPostOfficeMIS, calcCryptoProfit, calcFlatVsReducing,
} from '@/lib/calculations/finance';
import {
  calcOhmsLaw, calcResistor, calcPower, calcPythagorean, calcLedResistor, calcVoltDivider, calcBatteryLife, calcPcbTrace, calcDecibel, calcAntennaLen, calcTorque, calcBeamLoad, calcHeatExchanger, calcFluidFlow, calcSpringForce, calcGearRatio, calcInverterBattery, calcAcBtu, calcPipeFlow, calcThreePhase, calcTransformer,
  calcMotorSize, calcResistorDecode,
} from '@/lib/calculations/engineering';
import {
  calcConcrete, calcBricks, calcPaint, calcFlooring, calcSteel, calcRoofing, calcEarthwork, calcPlasterwork, calcWaterTank, calcLandArea, calcStampDuty, calcConstructionCost, calcSolarPanel, calcHomeRenovation, calcConcreteMix, calcMaterialWaste, calcRainwater,
  calcStaircase, calcSepticTank, calcElectricalLoad,
  calcFenceWall, calcWaterproofing, calcFalseCeiling, calcColumnFooting, calcWindowDoor, calcSandGravel, calcScaffolding, calcCarpetArea,
} from '@/lib/calculations/construction';
import {
  calcSpeedDist, calcNewtons, calcOhmAdvanced, calcDensity, calcChemMolar, calcWavelength, calcGravitational, calcHalfLife, calcPH, calcKinematic, calcThermodynamics, calcAcceleration,
  calcIdealGas, calcCoulombsLaw, calcEscapeVelocity, calcSoundSpeed,
} from '@/lib/calculations/science';
import {
  calcDateDiff, calcTimeConv, calcCountdown, calcTimezone, calcWorkingDays, calcAgeNextBday, calcRetirementDate, calcAgeUnits,
  calcLeapYear, calcWeekNumber, calcDateAdd,
} from '@/lib/calculations/datetime';
import {
  calcLength, calcWeight, calcTemperature, calcArea, calcSpeed, calcCurrency, calcVolume, calcData, calcPressure, calcEnergy, calcAngle,
  calcFuelEfficiency, calcNumberWord, calcCookingConvert,
} from '@/lib/calculations/unit';
import {
  calcBMI, calcBMR, calcTDEE, calcWater, calcHeartRate, calcAge, calcCalories, calcSleep, calcMacros, calcPregnancy, calcIdealWeight, calcOvulation, calcBloodPressure, calcAlcohol, calcWaistHip, calcIBW, calcVitamins, calcLungCapacity, calcBodyFat, calcProteinIntake, calcSmokingCost, calcChildHeight, calcDiabetesRisk, calcSleepDebt, calcAnemia, calcBSA, calcCholesterolRatio, calcCalorieDeficit, calcOneRepMax, calcRunningPace, calcBodyRecomp, calcVO2Max, calcLeanBodyMass, calcCalorieGoal, calcElectrolyte, calcIntermittentFasting, calcWaistHeightRatio,
  calcPregnancyWeight, calcBreastmilk, calcStepCounter, calcBACDetailed, calcMenstrualCycle,
} from '@/lib/calculations/health';
import {
  calcPercentage, calcRatio, calcSquareRoot, calcLogarithm, calcFactorial, calcQuadratic, calcPrime, calcNumberSystem, calcAverage, calcStatistics, calcMatrix2x2, calcCombinations, calcLcmGcd, calcRomanNumeral, calcTriangleArea, calcScientific, calcFraction, calcStdDev, calcLinearEq, calcCircleCalc, calcDeterminant, calcComplexNum,
} from '@/lib/calculations/math';
import {
  calcTip, calcDiscount, calcFuel, calcSalary, calcEmi2, calcGrade, calcElectricBill, calcLoanAffordability, calcCaloriesFood, calcWireSize, calcPixelResolution, calcTypingSpeed, calcEmiExtra, calcInvestVsRent, calcUnitPrice, calcPetrolParity, calcLaundry, calcWeddingBudget, calcRentAfford, calcFreelanceRate, calcCarbonFootprint, calcCarTco, calcTipSplit, calcPetAge, calcTravelBudget, calcMileage, calcCooking, calcShoeSize, calcStopwatch, calcRandomNum, calcEvPetrolSavings, calcEcomProfit, calcRestaurantCost, calcSubscriptionPricing, calcUnitEconomics, calcEventBudget, calcHouseholdBudget, calcDataUsage,
  calcInflationBasket, calcPhonePlan, calcMovingCost, calcLaundryLoad,
} from '@/lib/calculations/everyday';
import {
  calcCgpa, calcExamNeeded, calcEduLoan, calcStudyHours, calcScholarship, calcPomodoro, calcGpaConverter, calcReadingTime, calcTypingTest, calcSpellingBee, calcAttendance, calcGpaPlanner, calcPercentile, calcCutoffPredictor, calcRevisionPlanner, calcCgpaToPercentage,
  calcMarksPercentage, calcCompetitiveExam, calcBacklogRecovery, calcResearchMetrics, calcAbroadCost,
} from '@/lib/calculations/education';
import {
  calcPasswordStrength, calcWordCounter, calcAspectRatio, calcSocialMediaImage, calcDogAge,
  calcSubnet, calcBandwidth, calcColorConverter,
  calcJsonFormatter,
} from '@/lib/calculations/tech';

const calcRegistry: Record<string, CalcFunction> = {
  tip: calcTip,
  discount: calcDiscount,
  fuel: calcFuel,
  salary: calcSalary,
  emi2: calcEmi2,
  grade: calcGrade,
  electricbill: calcElectricBill,
  loanaffordability: calcLoanAffordability,
  caloriesfood: calcCaloriesFood,
  wiresize: calcWireSize,
  pixelresolution: calcPixelResolution,
  typing_speed: calcTypingSpeed,
  emi_extra: calcEmiExtra,
  investVsRent: calcInvestVsRent,
  unitPrice: calcUnitPrice,
  petrolParity: calcPetrolParity,
  laundry: calcLaundry,
  weddingbudget: calcWeddingBudget,
  rentafford: calcRentAfford,
  freelancerate: calcFreelanceRate,
  carbonfootprint: calcCarbonFootprint,
  cartco: calcCarTco,
  tipsplit: calcTipSplit,
  petage: calcPetAge,
  travelbudget: calcTravelBudget,
  mileage: calcMileage,
  cooking: calcCooking,
  shoesize: calcShoeSize,
  stopwatch: calcStopwatch,
  randomnum: calcRandomNum,
  evpetrolsavings: calcEvPetrolSavings,
  ecomprofit: calcEcomProfit,
  restaurantcost: calcRestaurantCost,
  subscriptionpricing: calcSubscriptionPricing,
  uniteconomics: calcUnitEconomics,
  eventbudget: calcEventBudget,
  householdbudget: calcHouseholdBudget,
  dataUsage: calcDataUsage,
  cgpa: calcCgpa,
  examneeded: calcExamNeeded,
  eduloan: calcEduLoan,
  studyhours: calcStudyHours,
  scholarship: calcScholarship,
  pomodoro: calcPomodoro,
  gpaconverter: calcGpaConverter,
  readingtime: calcReadingTime,
  typingtest: calcTypingTest,
  spellingbee: calcSpellingBee,
  attendance: calcAttendance,
  gpaplanner: calcGpaPlanner,
  percentile: calcPercentile,
  cutoffpredictor: calcCutoffPredictor,
  revisionplanner: calcRevisionPlanner,
  cgpaToPercentage: calcCgpaToPercentage,
  emi: calcEMI,
  sip: calcSIP,
  gst: calcGST,
  pregst: calcPreGST,
  compoundinterest: calcCompoundInterest,
  simpleinterest: calcSimpleInterest,
  incometax: calcIncomeTax,
  roi: calcROI,
  ppf: calcPPF,
  fd: calcFD,
  mortgage: calcMortgage,
  carloan: calcCarLoan,
  breakeven: calcBreakeven,
  inflation: calcInflation,
  swp: calcSWP,
  lumpsum: calcLumpsum,
  nps: calcNPS,
  gratuity: calcGratuity,
  hra: calcHRA,
  cagr: calcCAGR,
  creditcard: calcCreditCard,
  networth: calcNetWorth,
  tds: calcTDS,
  epf: calcEPF,
  profitloss: calcProfitLoss,
  stockreturn: calcStockReturn,
  mutualfundreturns: calcMutualFundReturns,
  taxregime: calcTaxRegime,
  capitalgains: calcCapitalGains,
  prepayment: calcPrepayment,
  stepupsip: calcStepUpSIP,
  savingsgoal: calcSavingsGoal,
  dividendyield: calcDividendYield,
  goldinvestment: calcGoldInvestment,
  rd: calcRD,
  xirr: calcXIRR,
  loaneligibility: calcLoanEligibility,
  balancetransfer: calcBalanceTransfer,
  ssy: calcSSY,
  scss: calcSCSS,
  advancetax: calcAdvanceTax,
  inhandsalary: calcInhandSalary,
  ctcbreakup: calcCtcBreakup,
  salarycomparison: calcSalaryComparison,
  goalsip: calcGoalSIP,
  elssreturns: calcElssReturns,
  nsc: calcNSC,
  apy: calcAPY,
  brokerage: calcBrokerage,
  taxsaving: calcTaxSaving,
  retirementcorpus: calcRetirementCorpus,
  salaryhike: calcSalaryHike,
  fire: calcFIRE,
  debtavalanche: calcDebtAvalanche,
  emergencyfund: calcEmergencyFund,
  rentvsbuy: calcRentVsBuy,
  carleasevsbuy: calcCarLeaseVsBuy,
  homedownpayment: calcHomeDownPayment,
  loancompare: calcLoanCompare,
  refinance: calcRefinance,
  creditutil: calcCreditUtil,
  insuranceneed: calcInsuranceNeed,
  npvirr: calcNpvIrr,
  bondyield: calcBondYield,
  optionprofit: calcOptionProfit,
  forexpip: calcForexPip,
  portfoliorebalance: calcPortfolioRebalance,
  assetallocation: calcAssetAllocation,
  montecarlo: calcMonteCarlo,
  inflationgoal: calcInflationGoal,
  businessloan: calcBusinessLoan,
  gstinvoice: calcGstInvoice,
  esoptax: calcEsopTax,
  freelancetax: calcFreelanceTax,
  tcsremittance: calcTcsRemittance,
  sec80c: calcSec80c,
  hravshomeloan: calcHraVsHomeLoan,
  proftax: calcProfTax,
  leaveencash: calcLeaveEncash,
  sgb: calcSGB,
  foTurnover: calcFoTurnover,
  presumptiveTax: calcPresumptiveTax,
  homeloanTaxBenefit: calcHomeLoanTaxBenefit,
  indexedCost: calcIndexedCost,
  goldComparison: calcGoldComparison,
  rentYield: calcRentYield,
  ohmslaw: calcOhmsLaw,
  resistor: calcResistor,
  power: calcPower,
  pythagorean: calcPythagorean,
  ledresistor: calcLedResistor,
  voltdivider: calcVoltDivider,
  batterylife: calcBatteryLife,
  pcbtrace: calcPcbTrace,
  decibel: calcDecibel,
  antennalen: calcAntennaLen,
  torque: calcTorque,
  beamload: calcBeamLoad,
  heatexchanger: calcHeatExchanger,
  fluidflow: calcFluidFlow,
  springforce: calcSpringForce,
  gearratio: calcGearRatio,
  inverterbattery: calcInverterBattery,
  acbtu: calcAcBtu,
  pipeflow: calcPipeFlow,
  threephase: calcThreePhase,
  transformercalc: calcTransformer,
  concrete: calcConcrete,
  bricks: calcBricks,
  paint: calcPaint,
  flooring: calcFlooring,
  steel: calcSteel,
  roofing: calcRoofing,
  earthwork: calcEarthwork,
  plasterwork: calcPlasterwork,
  waterTank: calcWaterTank,
  landarea: calcLandArea,
  stampdutycalc: calcStampDuty,
  constructioncost: calcConstructionCost,
  solarpanel: calcSolarPanel,
  homerenovation: calcHomeRenovation,
  concretemix: calcConcreteMix,
  materialwaste: calcMaterialWaste,
  rainwater: calcRainwater,
  speed_dist: calcSpeedDist,
  newtons: calcNewtons,
  ohm_advanced: calcOhmAdvanced,
  density: calcDensity,
  chemMolar: calcChemMolar,
  wavelength: calcWavelength,
  gravitational: calcGravitational,
  halflife: calcHalfLife,
  ph: calcPH,
  kinematicCalc: calcKinematic,
  thermodynamics: calcThermodynamics,
  acceleration: calcAcceleration,
  dateiff: calcDateDiff,
  timeconv: calcTimeConv,
  countdown: calcCountdown,
  timezone: calcTimezone,
  workingdays: calcWorkingDays,
  agenextbday: calcAgeNextBday,
  retirementDate: calcRetirementDate,
  ageUnits: calcAgeUnits,
  length: calcLength,
  weight: calcWeight,
  temperature: calcTemperature,
  area: calcArea,
  speed: calcSpeed,
  currency: calcCurrency,
  volume: calcVolume,
  data: calcData,
  pressure: calcPressure,
  energy: calcEnergy,
  angle: calcAngle,
  bmi: calcBMI,
  bmr: calcBMR,
  tdee: calcTDEE,
  water: calcWater,
  heartrate: calcHeartRate,
  age: calcAge,
  calories: calcCalories,
  sleep: calcSleep,
  macros: calcMacros,
  pregnancy: calcPregnancy,
  idealweight: calcIdealWeight,
  ovulation: calcOvulation,
  bloodpressure: calcBloodPressure,
  alcohol: calcAlcohol,
  waisthip: calcWaistHip,
  ibw: calcIBW,
  vitamins: calcVitamins,
  lungcapacity: calcLungCapacity,
  bodyfat: calcBodyFat,
  proteinintake: calcProteinIntake,
  smokingcost: calcSmokingCost,
  childheight: calcChildHeight,
  diabetesrisk: calcDiabetesRisk,
  sleepdebt: calcSleepDebt,
  anemia: calcAnemia,
  bsa: calcBSA,
  cholesterolratio: calcCholesterolRatio,
  caloriedeficit: calcCalorieDeficit,
  onerepmax: calcOneRepMax,
  runningpace: calcRunningPace,
  bodyrecomp: calcBodyRecomp,
  vo2max: calcVO2Max,
  leanbodymass: calcLeanBodyMass,
  caloriegoal: calcCalorieGoal,
  electrolyte: calcElectrolyte,
  intermittentFasting: calcIntermittentFasting,
  waistHeightRatio: calcWaistHeightRatio,
  percentage: calcPercentage,
  ratio: calcRatio,
  squareroot: calcSquareRoot,
  logarithm: calcLogarithm,
  factorial: calcFactorial,
  quadratic: calcQuadratic,
  prime: calcPrime,
  numbersystem: calcNumberSystem,
  average: calcAverage,
  statistics: calcStatistics,
  matrix2x2: calcMatrix2x2,
  combinations: calcCombinations,
  lcmgcd: calcLcmGcd,
  romanNumeral: calcRomanNumeral,
  triangleArea: calcTriangleArea,
  scientific: calcScientific,
  fraction: calcFraction,
  stddev: calcStdDev,
  lineareq: calcLinearEq,
  circleCalc: calcCircleCalc,
  determinant: calcDeterminant,
  complexnum: calcComplexNum,
  // Phase 1 — New Finance
  emivstenure: calcEmiVsTenure,
  ruleof72: calcRuleOf72,
  postofficemis: calcPostOfficeMIS,
  cryptoprofit: calcCryptoProfit,
  flatvsreducing: calcFlatVsReducing,
  // Phase 1 — New Health
  pregnancyweight: calcPregnancyWeight,
  breastmilk: calcBreastmilk,
  stepcounter: calcStepCounter,
  bacdetailed: calcBACDetailed,
  menstrualcycle: calcMenstrualCycle,
  // Phase 1 — New Tech & Everyday
  passwordstrength: calcPasswordStrength,
  wordcounter: calcWordCounter,
  aspectratio: calcAspectRatio,
  socialmediaimage: calcSocialMediaImage,
  dogage: calcDogAge,
  // Phase 1 — Tech category
  subnet: calcSubnet,
  bandwidth: calcBandwidth,
  colorconverter: calcColorConverter,
  // Phase 2 — Science
  idealGas: calcIdealGas,
  coulombsLaw: calcCoulombsLaw,
  escapeVelocity: calcEscapeVelocity,
  soundSpeed: calcSoundSpeed,
  // Phase 2 — Date & Time
  leapYear: calcLeapYear,
  weekNumber: calcWeekNumber,
  dateAdd: calcDateAdd,
  // Phase 2 — Unit Conversion
  fuelEfficiency: calcFuelEfficiency,
  numberWord: calcNumberWord,
  cookingConvert: calcCookingConvert,
  // Phase 2 — Education
  marksPercentage: calcMarksPercentage,
  competitiveExam: calcCompetitiveExam,
  backlogRecovery: calcBacklogRecovery,
  researchMetrics: calcResearchMetrics,
  abroadCost: calcAbroadCost,
  // Phase 3 — Everyday
  inflationBasket: calcInflationBasket,
  phonePlan: calcPhonePlan,
  movingCost: calcMovingCost,
  laundryLoad: calcLaundryLoad,
  // Phase 3 — Tech & Engineering
  jsonFormatter: calcJsonFormatter,
  motorSize: calcMotorSize,
  resistorDecode: calcResistorDecode,
  // Phase 3 — Construction
  staircase: calcStaircase,
  septicTank: calcSepticTank,
  electricalLoad: calcElectricalLoad,
  // Phase 4 — New Construction
  fenceWall: calcFenceWall,
  waterproofing: calcWaterproofing,
  falseCeiling: calcFalseCeiling,
  columnFooting: calcColumnFooting,
  windowDoor: calcWindowDoor,
  sandGravel: calcSandGravel,
  scaffolding: calcScaffolding,
  carpetArea: calcCarpetArea,
};

export function getCalcFunction(calcId: string): CalcFunction | null {
  return calcRegistry[calcId] || null;
}
