'use client';

import React from 'react';
import {
  Landmark,
  Activity,
  Calculator,
  Lightbulb,
  GraduationCap,
  Settings,
  Shield,
  Clock,
  FlaskConical,
  ArrowLeftRight,
  Percent,
  Equal,
  Variable,
  AlertCircle,
  Hash,
  Code,
  BarChart2,
  Table,
  Dices,
  Type,
  Circle,
  Infinity as InfinityIcon,
  Sprout,
  FileText,
  FileCheck,
  Coins,
  TrendingUp,
  PiggyBank,
  Lock,
  Home,
  Car,
  Scale,
  Flame,
  Send,
  DollarSign,
  UserCheck,
  Handshake,
  CreditCard,
  Briefcase,
  Target,
  Trophy,
  Baby,
  User,
  CalendarCheck,
  Receipt,
  Leaf,
  Umbrella,
  Accessibility,
  Footprints,
  Plane,
  Gauge,
  Utensils,
  Timer,
  BatteryCharging,
  Apple,
  GitFork,
  Box,
  Globe,
  Radio,
  Thermometer,
  Building,
  Grid,
  Paintbrush,
  ListTodo,
  Truck,
  Layers,
  Waves,
  Map,
  Sun,
  FileEdit,
  BookOpen,
  Medal,
  Keyboard,
  SpellCheck,
  RotateCcw,
  Laptop,
  MapPin,
  Dumbbell,
  Droplet,
  ClipboardCheck,
  Award,
  Sparkles,
  Calendar,
  Battery,
  Snowflake,
  Ruler,
  Bolt,
  Maximize2,
  ShoppingCart,
  Repeat,
  Hourglass,
  Wifi,
  Newspaper,
  Menu,
  Search,
  Moon,
  ChevronRight,
  ChevronDown,
  Recycle,
  CloudRain,
  X,
  Bug,
  MessageCircle,
  CheckCircle2,
  Star,
  Heart,
  Copy,
  Download,
  Share2,
  Link2,
  Printer,
  ThumbsDown,
  ThumbsUp,
  Frown,
  Meh,
  Smile,
  PartyPopper,
  Info,
  AlertTriangle,
  CircleAlert,
  Crosshair,
  Utensils as UtensilsIcon,
  Zap,
  ArrowLeft,
  Mail,
  Trash2,
  History,
  Eraser,
  FileSignature,
  Cookie,
  HeartPulse,
  Cake,
  PieChart,
  CigaretteOff,
  Syringe,
  IndianRupee,
  HardDrive,
  Compass,
  Cpu,
  Volume2,
  Fuel,
  Shirt,
  Hospital,
  Bed,
  Book,
  Tags,
  Plug,
  Image,
  Tag,
  Square,
  GlassWater,
  AtSign
} from 'lucide-react';

const iconMap: Record<string, React.ComponentType<{ className?: string; style?: React.CSSProperties }>> = {
  // Navigation & General
  'fa-house': Home,
  'fa-chart-line': TrendingUp,
  'fa-newspaper': Newspaper,
  'fa-bars': Menu,
  'fa-search': Search,
  'fa-moon': Moon,
  'fa-sun': Sun,
  'fa-chevron-right': ChevronRight,
  'fa-chevron-down': ChevronDown,

  // Categories
  'fa-landmark': Landmark,
  'fa-heartbeat': Activity,
  'fa-calculator': Calculator,
  'fa-lightbulb': Lightbulb,
  'fa-graduation-cap': GraduationCap,
  'fa-gear': Settings,
  'fa-helmet-safety': Shield, // Map to Shield since HardHat is not default
  'fa-clock': Clock,
  'fa-flask': FlaskConical,
  'fa-right-left': ArrowLeftRight,

  // Specific Calculator Icons
  'fa-percent': Percent,
  'fa-equals': Equal,
  'fa-square-root-variable': Variable,
  'fa-wave-square': Activity,
  'fa-exclamation': AlertCircle,
  'fa-superscript': Type,
  'fa-hashtag': Hash,
  'fa-code': Code,
  'fa-chart-simple': BarChart2,
  'fa-chart-column': BarChart2,
  'fa-table-cells': Table,
  'fa-dice': Dices,
  'fa-divide': Percent,
  'fa-i-cursor': Type,
  'fa-draw-polygon': Box,
  'fa-circle': Circle,
  'fa-infinity': InfinityIcon,
  'fa-building-columns': Landmark,
  'fa-seedling': Sprout,
  'fa-file-invoice': FileText,
  'fa-file-invoice-dollar': FileCheck,
  'fa-file-lines': FileText,
  'fa-coins': Coins,
  'fa-arrow-trend-up': TrendingUp,
  'fa-piggy-bank': PiggyBank,
  'fa-vault': Lock,
  'fa-car': Car,
  'fa-scale-balanced': Scale,
  'fa-fire-flame-curved': Flame,
  'fa-money-bill-transfer': Send,
  'fa-sack-dollar': DollarSign,
  'fa-user-shield': UserCheck,
  'fa-handshake': Handshake,
  'fa-house-chimney': Home,
  'fa-credit-card': CreditCard,
  'fa-scale-unbalanced-flip': Scale,
  'fa-briefcase': Briefcase,
  'fa-arrow-up-right-dots': TrendingUp,
  'fa-house-circle-check': Home,
  'fa-stairs': TrendingUp,
  'fa-bullseye': Target,
  'fa-trophy': Trophy,
  'fa-child': Baby,
  'fa-user-tie': User,
  'fa-calendar-check': CalendarCheck,
  'fa-receipt': Receipt,
  'fa-code-compare': ArrowLeftRight,
  'fa-leaf': Leaf,
  'fa-stamp': Shield,
  'fa-umbrella': Umbrella,
  'fa-chart-candlestick': BarChart2,
  'fa-person-cane': Accessibility,
  'fa-weight-scale': Scale,
  'fa-paw': Footprints,
  'fa-plane-departure': Plane,
  'fa-gauge-high': Gauge,
  'fa-kitchen-set': Utensils,
  'fa-shoe-prints': Footprints,
  'fa-stopwatch': Timer,
  'fa-charging-station': BatteryCharging,
  'fa-person-running': Activity,
  'fa-apple-whole': Apple,
  'fa-circle-nodes': GitFork,
  'fa-cube': Box,
  'fa-flask-vial': FlaskConical,
  'fa-earth-americas': Globe,
  'fa-radiation': Radio,
  'fa-satellite': Plane,
  'fa-temperature-arrow-up': Thermometer,
  'fa-gauge-simple-high': Gauge,
  'fa-building': Building,
  'fa-border-all': Grid,
  'fa-paint-roller': Paintbrush,
  'fa-grip': Grid,
  'fa-bars-progress': ListTodo,
  'fa-tractor': Truck,
  'fa-layer-group': Layers,
  'fa-water': Waves,
  'fa-map': Map,
  'fa-solar-panel': Sun,
  'fa-file-pen': FileEdit,
  'fa-book-open': BookOpen,
  'fa-medal': Medal,
  'fa-book-open-reader': BookOpen,
  'fa-keyboard': Keyboard,
  'fa-spell-check': SpellCheck,
  'fa-fire': Flame,
  'fa-money-bill-wave': DollarSign,
  'fa-shield-halved': Shield,
  'fa-car-side': Car,
  'fa-rotate': RotateCcw,
  'fa-chart-gantt': BarChart2,
  'fa-money-bill-trend-up': TrendingUp,
  'fa-dice-d20': Dices,
  'fa-laptop-code': Laptop,
  'fa-house-lock': Lock,
  'fa-map-location-dot': MapPin,
  'fa-dumbbell': Dumbbell,
  'fa-person-arrow-up-from-line': TrendingUp,
  'fa-lungs': Activity,
  'fa-utensils': Utensils,
  'fa-glass-water-droplet': Droplet,
  'fa-clipboard-check': ClipboardCheck,
  'fa-ranking-star': Award,
  'fa-crystal-ball': Sparkles,
  'fa-calendar-days': Calendar,
  'fa-car-battery': Battery,
  'fa-snowflake': Snowflake,
  'fa-ruler-combined': Ruler,
  'fa-faucet-drip': Droplet,
  'fa-bolt': Bolt,
  'fa-temperature-half': Thermometer,
  'fa-compress': Maximize2,
  'fa-gears': Settings,
  'fa-cubes-stacked': Layers,
  'fa-recycle': Recycle,
  'fa-cloud-rain': CloudRain,
  'fa-cart-shopping': ShoppingCart,
  'fa-repeat': Repeat,
  'fa-chart-bar': BarChart2,
  'fa-calendar-day': Calendar,
  'fa-house-user': Home,
  'fa-ruler-vertical': Ruler,
  'fa-hourglass-half': Hourglass,
  'fa-wifi': Wifi,
  // New icons for emoji replacement
  'fa-xmark': X,
  'fa-x': X,
  'fa-bug': Bug,
  'fa-comment': MessageCircle,
  'fa-message': MessageCircle,
  'fa-circle-check': CheckCircle2,
  'fa-check-circle': CheckCircle2,
  'fa-star': Star,
  'fa-heart': Heart,
  'fa-copy': Copy,
  'fa-download': Download,
  'fa-share': Share2,
  'fa-link': Link2,
  'fa-print': Printer,
  'fa-thumbs-down': ThumbsDown,
  'fa-thumbs-up': ThumbsUp,
  'fa-frown': Frown,
  'fa-meh': Meh,
  'fa-smile': Smile,
  'fa-party-popper': PartyPopper,
  'fa-info-circle': Info,
  'fa-info': Info,
  'fa-triangle-exclamation': AlertTriangle,
  'fa-warning': AlertTriangle,
  'fa-circle-exclamation': CircleAlert,
  'fa-crosshair': Crosshair,
  'fa-utensils-alt': UtensilsIcon,
  'fa-zap': Zap,

  // New Missing Actions & Navigation Mappings
  'fa-arrow-left': ArrowLeft,
  'fa-envelope': Mail,
  'fa-location-dot': MapPin,
  'fa-paper-plane': Send,
  'fa-trash-can': Trash2,
  'fa-clock-rotate-left': History,
  'fa-eraser': Eraser,
  'fa-file-signature': FileSignature,
  'fa-circle-question': HelpCircleIcon,
  'fa-readme': BookOpen,
  'fa-lock': Lock,
  'fa-redo': RotateCcw,
  'fa-cookie-bite': Cookie,
  'fa-magnifying-glass-chart': BarChart2,
  
  // New Calculator Domain Mappings
  'fa-hand-holding-dollar': Coins,
  'fa-droplet': Droplet,
  'fa-heart-pulse': HeartPulse,
  'fa-birthday-cake': Cake,
  'fa-chart-pie': PieChart,
  'fa-baby': Baby,
  'fa-weight-hanging': Scale,
  'fa-calendar-heart': CalendarCheck,
  'fa-wine-glass': GlassWater,
  'fa-ruler-horizontal': Ruler,
  'fa-user-check': UserCheck,
  'fa-person': User,
  'fa-ban-smoking': CigaretteOff,
  'fa-child-reaching': Accessibility,
  'fa-syringe': Syringe,
  'fa-person-dots-from-line': TrendingUp,
  'fa-heart-circle-check': Heart,
  'fa-ruler': Ruler,
  'fa-vector-square': Square,
  'fa-indian-rupee-sign': IndianRupee,
  'fa-hard-drive': HardDrive,
  'fa-drafting-compass': Compass,
  'fa-globe': Globe,
  'fa-cake-candles': Cake,
  'fa-bolt-lightning': Zap,
  'fa-microchip': Cpu,
  'fa-plug-circle-bolt': Zap,
  'fa-battery-half': Battery,
  'fa-volume-high': Volume2,
  'fa-tower-broadcast': Radio,
  'fa-tag': Tag,
  'fa-gas-pump': Fuel,
  'fa-house-flag': Home,
  'fa-plug': Plug,
  'fa-image': Image,
  'fa-house-circle-xmark': Home,
  'fa-shirt': Shirt,
  'fa-ring': Coins,

  // New Interpretation & Alert Mappings
  'fa-sparkles': Sparkles,
  'fa-file-certificate': Award,
  'fa-umbrella-beach': Umbrella,
  'fa-hospital': Hospital,
  'fa-calendar': Calendar,
  'fa-running': Activity,
  'fa-bed': Bed,
  'fa-book': Book,
  'fa-hand-holding-heart': Heart,
  'fa-tags': Tags,
  'fa-user': User,
  'fa-at': AtSign,
};

interface IconProps {
  name: string;
  className?: string;
  style?: React.CSSProperties;
}

export default function Icon({ name, className, style }: IconProps) {
  // Strip fas/far/fab prefix and potential extra classes
  const cleanName = name
    .replace(/^(fas|far|fab|fa)\s+/, '')
    .trim()
    .split(/\s+/)[0];

  const LucideIcon = iconMap[cleanName] || iconMap[`fa-${cleanName}`] || HelpCircleIcon;

  return <LucideIcon className={className} style={style} />;
}

// Fallback icon
function HelpCircleIcon({ className, style }: { className?: string; style?: React.CSSProperties }) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      className={className}
      style={style}
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3" />
      <line x1="12" y1="17" x2="12.01" y2="17" />
    </svg>
  );
}
